<?xml version="1.0"?>

<root xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find road_description)/urdf/roads/road.gazebo" />
  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:macro name="road" params="parent:=road_base_link name:=road size:=1.0 dae:=straight thickness:=0.02 *origin">

    <joint name="joint_${name}_parent_to_link" type="fixed">
      <xacro:insert_block name="origin" /> 
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <!--<inertial>
        <mass value="100"/>
        <origin xyz="0 0 ${thickness/2}" rpy="0 0 0"/>
        <inertia ixx="21.33933333" ixy="0" ixz="0" iyy="13.73933333" iyz="0" izz="35.07266667" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${thickness/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${size} ${size} ${thickness}"/>
        </geometry>
        <material name="green"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${thickness/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${size} ${size} ${thickness}"/>
        </geometry>
      </collision>-->
    </link>

    <joint name="joint_${name}_link_to_image" type="fixed">
      <origin xyz="0 0 ${thickness+0.001}" rpy="${PI/2} 0 -${PI/2}" />
      <parent link="${name}_link"/>
      <child link="${name}_image" />
    </joint>

    <link name="${name}_image">
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://road_description/urdf/roads/dae/${dae}.dae" scale="${size} 1.0 ${size}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://road_description/urdf/roads/dae/${dae}.dae" scale="${size} 1.0 ${size}"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>

</root>

