<?xml version="1.0"?>

<root xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find road_description)/urdf/materials.xacro" />
  <xacro:property name="default_side" value="10.0" />
  <xacro:property name="default_width" value="2.0" />
  <xacro:property name="default_thick" value="0.02" />

  <xacro:macro name="ceiling" 
               params="parent:=ceiling_base_link 
                       name:=ceiling 
                       *origin 
                       x1:=${default_side}
                       y1:=${default_side}
                       x2:=${default_side}
                       y2:=-${default_side}
                       x3:=-${default_side}
                       y3:=${default_side}
                       width:=${default_width}
                       length:=${default_width}
                       thick:=${default_thick}">

    <joint name="joint_${name}_parent_to_link" type="fixed">
      <xacro:insert_block name="origin" /> 
      <parent link="${parent}"/>
      <child link="${name}"/>
    </joint>

    <link name="${name}">
    </link>

    <joint name="joint_${name}_to_lamp1" type="fixed">
      <origin xyz="${x1} ${y1} -${thick/2.0}" rpy="0 0 0" />
      <parent link="${name}"/>
      <child link="lamp1" />
    </joint>

    <link name="lamp1">
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${thick}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${thick}"/>
        </geometry>
      </collision>
    </link>

    <joint name="joint_${name}_to_lamp2" type="fixed">
      <origin xyz="${x2} ${y2} -${thick/2.0}" rpy="0 0 0" />
      <parent link="${name}"/>
      <child link="lamp2" />
    </joint>

    <link name="lamp2">
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${thick}"/>
        </geometry>
        <material name="green" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${thick}"/>
        </geometry>
      </collision>
    </link>

    <joint name="joint_${name}_to_lamp3" type="fixed">
      <origin xyz="${x3} ${y3} -${thick/2.0}" rpy="0 0 0" />
      <parent link="${name}"/>
      <child link="lamp3" />
    </joint>

    <link name="lamp3">
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${thick}"/>
        </geometry>
        <material name="blue" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${thick}"/>
        </geometry>
      </collision>
    </link>

    <gazebo>
      <static>1</static>
    </gazebo>

    <gazebo reference="ceiling">
      <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="lamp1">
      <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="lamp2">
      <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="lamp3">
      <material>Gazebo/Blue</material>
    </gazebo>

  </xacro:macro>

</root>